pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/naveengadde123/JMeterTesing.git'  // Your GitHub repository URL
        BRANCH = 'main'  // Your branch name
        CREDENTIALS_ID = '1d54e951-e865-4582-a541-e726548cfefd'  // Your credentials ID
        JMETER_HOME = 'C:/JMeter/apache-jmeter-5.6.3/apache-jmeter-5.6.3'  // Adjust this path to your JMeter installation
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning the Git repository...'
                // Cloning the specified branch from the repository and using the credentials
                git branch: "${BRANCH}", url: "${GIT_REPO}", credentialsId: "${CREDENTIALS_ID}"
            }
        }

        stage('Test JMeter') {
            steps {
                echo 'Running JMeter tests...'
                // Running JMeter tests with the .jmx file after cloning
                bat """
                    "${JMETER_HOME}/bin/jmeter.bat" -n -t "C:\\JMeter\\apache-jmeter-5.6.3\\apache-jmeter-5.6.3\\bin\\Test.jmx" -l "C:\\Training\\results.jtl" -JDuration=1 -Jusers=3
                """
            }
        }

        stage('Publish JMeter HTML Report') {
            steps {
                echo 'Publishing JMeter HTML Report...'
                publishHTML([ 
                    reportName: 'JMeter Report',
                    reportDir: 'C:\\Training', // Adjust this path to where your HTML report is generated
                    reportFiles: 'index.html', // The report file generated by JMeter
                    alwaysLinkToLastBuild: true, // Link to the last build in the report
                    allowMissing: false // Do not allow missing reports
                ])
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
